### ISSUE TITLE
OpenGL.Net.Objects Not Found

### ISSUE THREAD

**Issue by bryaan** [luca-piccioni/OpenGL.Net#104]
Wondering what happened to the OpenGL.Net.Objects nuget package.  What is the recommended way to get it?

**Comment by luca-piccioni** [comment]
I just removed the nuget package. If you want to use that piece of code, just compile it yourself.

**Comment by bryaan** [comment]
Any reason why? The utilities are important, like FontFactory.
This makes it tougher to keep up to date.

**Comment by bryaan** [comment]
I see that I'm going to have to compile from master anyway as there has been much work done since last publish.  Is there a reason why you haven't pushed a new version in so long?

**Comment by luca-piccioni** [comment]
Yeah. Initially, I was planning to generate nuget packages for _OpenGL.Net.Object_ also, along with the base library OpenGL.Net. After some time I realized that maintaining the only _OpenGL.Net_ project was enough for my free-time budget, despite the higher level library is more fun to develop.

From then, .NET Core support was added and the Android platform support was added too, and I got serious difficulties to keep those features available on _OpenGL.Net.Object_. Now I keep that project as an example of OpenGL framework development, but at the moment I can't afford any further development due to work and home duties.

I'm glad to hear that OpenGL.Net.Object is useful to you, but I suggest to manage that code-base yourself; I know that it can be hard, the code is quite complex and class coupling is very high, but once you got the basic knowledge of the GL objects management, you can extend the project for your needs.

**Comment by bryaan** [comment]
Luca, thank you for the explanation.  I am definitely impressed with your efforts here.  I hope more developers will find this library useful and help with it.

**Comment by tanaev** [comment]
@luca-piccioni Hey! But how to show *.mdl file for example, without OpenGL.Net.Objects? All samples use this implementation.

Thanks

**Comment by luca-piccioni** [comment]
What samples loads mdl files using OpenGL.Net.Objects? I'm not aware of.

Anyway, just compile the solution and use it.

**Comment by tanaev** [comment]
@luca-piccioni this file depends on OpenGL.Net.Objects for example. 
https://github.com/luca-piccioni/OpenGL.Net/blob/master/Samples/HelloObjects/SampleForm.cs

In other cases, what is the proper way to show mdl files in GLSurfaceView?
