### ISSUE TITLE
Alternative license?

### ISSUE THREAD

**Issue by codedivine** [luca-piccioni/OpenGL.Net#17]
Would you reconsider relicensing the project to something like MIT or BSD? LGPL license can pose problems on platforms like Android. For example, see this discussion: http://stackoverflow.com/questions/4916512/using-lgpl-library-in-paid-android-app

**Comment by luca-piccioni** [comment]
This issue is relevant also for managed applications running with mono?

Everything is packed into a jar archive? I don't know much about Android
internals, but how Google managed all OSS libraries included in the OS?

I'm reluctant to change the license. Maybe a dual license, but I prefer to
stick with copy left licenses.

Il Dom 16 Ott 2016 10:48 Rahul Garg <notifications@github.com> ha scritto:

**Comment by matyasf** [comment]
I just wanted to open an issue about this. The issue with LGPL is that users cannot link your library statically. This makes it a big headache to include it (I got no idea how to do it with Xamarin) and basically prevents commercial usage (e.g. in games). For example I am making a 2D framework and I'm considering to use your library. Mine is licenced under Apache 2.0, so if I include openGL.Net then I must get my users to accept 2 licences, and more importantly building will be a headache which will put off inexperienced users.

Android can get away with including LGPL libraries since its a huge project that will be built by professionals with big teams. My project is intended for both small hobbyists too, who would find a tricky build system off putting. 

I suggest to use Apache 2.0 (Android uses it too , see https://source.android.com/source/licenses.html also this doc argues why they did not went with LGPL too). Apache 2.0 is like the MIT license, you do what you want with an included clause that you will not try to get money from the users of openGL.net if you software patent parts of it.

**Comment by luca-piccioni** [comment]
The project has changed the licence; now it is using MIT. Check the readme.

**Comment by codedivine** [comment]
Thanks for the licensing change! Much appreciated!
