### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by BobCFD** [luca-piccioni/OpenGL.Net#2]
ShaderIncludeLibrary includeLibrary = ctx.IncludeLibrary;
this line shows ctx does not contans the definition of IncludeLibrary
Error	1	“OpenGL.GraphicsContext”  do not contains the definition of “IncludeLibrary”

**Comment by luca-piccioni** [comment]
I know. The library OpenGL.Hal is not meant to be used right now. Its
sources derive from an old project, and I use it to validate some of the
OpenGL.Net interface methods.

At the moment, only OpenGL.Net library is compilable and usable.

Maybe for the next year the OpenGL.Hal library can be used, but I'm
planning an heavy refactoring on it.

Il giorno Ven 18 Dic 2015 13:41 BobCFD <notifications@github.com> ha
scritto:

**Comment by BobCFD** [comment]
Thanks for your explaination.  
     Is there some example show how to use OpenGl.Net, For its hard to move my think mode from SharpGL to OpenGl.Net.

**Comment by luca-piccioni** [comment]
Check the OpenGL.Net.Test: there are some unit tests that setup an opengl context and execute some specific entry point. 

You can also take as reference the sources in OpenGL.Hal (even if it is more complex). 

However, you can use any OpenGL source, since the C# API is 1:1 with the C API (more more rich because overloads and strongly typed enums).
