### ISSUE TITLE
Target .Net 3.5?

### ISSUE THREAD

**Issue by thomz12** [luca-piccioni/OpenGL.Net#22]
Our applications runs on .Net 3.5, we can build a version of OpenGL.Net dll in 3.5 without any problems. Is there a reason why you target .Net 4.5?

**Comment by luca-piccioni** [comment]
Actually no. I think it should be sufficient .NET 3.5 (because extension methods), and with "minor" changes also .NET 2.0. Initially the project target was .NET 2.0.

Isn't there a way to load the binary from a .NET 3.5 application? In other words, is there any reason why I should not target .Net 4.5?

**Comment by thomz12** [comment]
Unfortunately it's not possible to load the binary because of the higher target. Visual studio gives us "reference not found exceptions". If you can retarget, it saves us the trouble of maintaining our own fork.
