### ISSUE TITLE
Mesa

### ISSUE THREAD

**Issue by equinox2k** [luca-piccioni/OpenGL.Net#28]
Wondering if the library works with Mesa and if so how would I set it up?

**Comment by luca-piccioni** [comment]
Yes, it should since MESA offers a compliant GL implementation. However, I tried running a sample on X11 runningon Raspberry PI 2,and fails during the glXSwapBuffers due an access violation exception. 

I've not investigated further since the GL on RPi2 based on mesa is a software implementation, while I can access to the Broadcom API via VC4, and get GLES acceleration without X.
