### ISSUE TITLE
Roadmap, license, users, and contributions

### ISSUE THREAD

**Issue by varon** [luca-piccioni/OpenGL.Net#3]
A few questions:

Could you please provide a license for this (Preferably in the root of the project)?
Is there any information or background information on the users of this library?
Is there a roadmap or project plan available?
Where can new contributors get involved?

**Comment by luca-piccioni** [comment]
All sources are LGPL2'ed. I can provide soon a GNU-like files with license text and author info (me, and only me atm). 

Roadmap is not defined (at least formally). I'm trying to integrate the OpenGL.Hal sources to have an utility library with an higher lever of abstraction. 

Users of this library? Who knows... It's open! Can you elaborate more? 

External contributions are welcome, however I've never considered the possibility until now.

**Comment by varon** [comment]
I would suggest an MIT like license for this, as it has potential to be used commercially; it certainly might encourage further contribution.

If you don't know of anyone, perhaps a bit of detail on what you're using it for would be great.

About contributors, the question is _where_ they can get involved - what are the obvious deficiencies? Where does the library need to get expanded? I'd suggest creating a few issues (that you know of) to help with this.

**Comment by luca-piccioni** [comment]
Thank you for the precious suggestions.

About licensing I don't agree, since LGPL2 does not prevent commercial distribution, nor linking to proprietary software. However, respect the MIT license, it enforces the community/customer  since the modified sources must be available (hopefully here, on GitHub).

I think I'll start to write wiki pages for learning how to update the OpenGL bindings from fresh XML specifications; in this way new users can update the library themself.

Successively, I'll open some issue on topic I'd like to see enhancements/correctness.
