### ISSUE TITLE
New enumerations for various function options

### ISSUE THREAD

**Issue by frabert** [luca-piccioni/OpenGL.Net#40]
In the spirit of creating a safe interface to OpenGL, I think the number of currently generated enumerations is too slim; for example, when using `FramebufferRenderbuffer` It would be nice to use an enumeration to specify the attachment, like `BufferAttachment.ColorAttachment0` instead of  `Gl.COLOR_ATTACHMENT0`.

On a bit of a side note, since I am willing to provide some such improvements but I don't really know where to start, could you provide something like a guideline on how to make such additions?

Keep up the great work 👍

**Comment by luca-piccioni** [comment]
Just updated the [wiki page](https://github.com/luca-piccioni/OpenGL.Net/wiki/GL-%5C-API-updates), describing how to re-generate OpenGL.Net. You can see [my issue](https://github.com/KhronosGroup/OpenGL-API/issues/2) for adding strongly typed arguments, and [my issue](https://github.com/KhronosGroup/OpenGL-API/issues/3) for updating/extending enumerations values (and you should close [your issue](https://github.com/KhronosGroup/OpenGL-API/issues/1), because resolved by [my pull request](https://github.com/KhronosGroup/OpenGL-Registry/pull/44)).

You could follow my pull request as model for directly pulling changes to _KhronosGroup/OpenGL-Registry_, and pulling same changes in _OpenGL.Net_. Then, following the instruction on the wiki, update the API.

**Comment by frabert** [comment]
Thanks, I will have a read!
