### ISSUE TITLE
How do I getting started with OpenGL.NET in .NET Core?

### ISSUE THREAD

**Issue by SirusDoma** [luca-piccioni/OpenGL.Net#81]
Hello, I'm trying to figure out how to get started with .NET Core?
Is there any nuget package specific for .NET Core? and what about windowing supports in .net core?

Thanks in advance

**Comment by luca-piccioni** [comment]
.NET Core projects are included in the `OpenGL.Net_VC15` solution, which can be opened using Visual Studio  2017 Preview 2. You can run a sample on relative to .NET Core.

No, at the moment there no nuget package including the .NET Core binaries, but it will soon.

About windowing. Nothing stops you since .NET Core support P/Invokes, indeed you can call native OS functions to manage windowing. To facilitate the creation of a window I've introduced a sub-project named OpenGL.Net.CoreUI, which should abstract various OS windowing with a `NativeWindow` instance; however, currently support only Windows and it does not manage keyboard and mouse inputs.

**Comment by SirusDoma** [comment]
Thank you for your answer
Looking forward for the OpenGL.NET.CoreUI!
