### ISSUE TITLE
How to create a debug context

### ISSUE THREAD

**Issue by MichaelEwe** [luca-piccioni/OpenGL.Net#9]
Big thanks for this alternative to OpenTK

Currently I am rendering OpenGL content within a WPF application. I cannot host your `GlControl` in a `WindowsFormsHost`, because the entire HAL namespace is not part of the nuget package, and I want to stick to that.

So my way is to create a Window and a OpenGL context on my own and host it in a `HwndHost`.This works out fine. But I cannot figure out, how to set the callback function for a debug context.
```
object userParam = someObjectOfInterest;
IntPtr callback = ???;
OpenGL.Gl.DebugMessageCallback(callback, userParam);
```
How do I obtain an Intptr to my callback function? A delegate for the callback itself does not seem to exist.

**Comment by luca-piccioni** [comment]
The [GlControl](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net/GlControl.cs) is included in OpenGL.Net (and an older version is included in NuGet package also). However, that's fine also to manage your hosting handle yourself since you have all the API available.

Actually I typed the debug callback as IntPtr; this is correct but requires you to manage the delegate definition and the use of [GetFunctionPointerForDelegate](https://msdn.microsoft.com/en-us/library/at4fb09f(v=vs.100).aspx).

I'm working right now to include the required definitions (lazy mode is on).

**Comment by luca-piccioni** [comment]
This [commit](https://github.com/luca-piccioni/OpenGL.Net/commit/091b297b946119e7744bb0c20f975fdd31b933b4) will solve your issue.

**Comment by MichaelEwe** [comment]
Very nice, thank you very much!
